### ISSUE TITLE
Could not launch auvaltool internal error

### ISSUE THREAD

**Issue by jordan314** [olilarkin/wdl-ol#120] opened 2018-08-16 22:46 UTC
When I try to open and build the AU in the demo IPlugEffect in Xcode 9.4.1 in OS X 10.13.6, the build succeeds but then I get "Could not launch auvaltool - internal error." When I try validating it in Logic, the validator crashes.

**Comment by kyr0** [comment] 2018-08-23 21:31
I ran into the very same issue:

<img width="527" alt="bildschirmfoto 2018-08-23 um 22 32 29" src="https://user-images.githubusercontent.com/454817/44550822-a34a8a80-a725-11e8-92f9-a475f5bcc1bf.png">

So I digged a little deeper and I found the reasons for it: 
- `auvaltool` executable can't be found / or is not reachable to Xcode for execution (maybe security considerations)
- the schema is configured to debug `auvaltool` but it doesn't contain the correct debug symbols! 
- the build step to build the AU in XCode is set up with dummy data to call `auvaltool`. 

- *Option A*: Disable the "Run" task in Xcode and run `auval` in a terminal on your own like this _with the correct arguments that match your plugin id's_: auval -v aufx $PLUG_UNIQUE_ID $PLUG_MFR_ID, i.e.: `auval -v aufx Lapa AHVI` 

<img width="409" alt="bildschirmfoto 2018-08-23 um 23 27 09" src="https://user-images.githubusercontent.com/454817/44552911-1b1bb380-a72c-11e8-8dea-16faca5958a0.png">

<img width="377" alt="bildschirmfoto 2018-08-23 um 23 27 22" src="https://user-images.githubusercontent.com/454817/44552916-1d7e0d80-a72c-11e8-9351-0569e8ce06ff.png">

- *Option B*: Fix the schema config in Xcode like this:

1) Open a terminal and run: `cp /usr/bin/auval /Applications/auval`. This will copy the binary of `auval` (auvaltool is only a symbolic link) -- and place it into a place your user can reach without any security limitation.

2) We gonna fix the schema config:

3) Take a look into your `resource.h`. Note the values of `PLUG_UNIQUE_ID` and `PLUG_MFR_ID`:

<img width="548" alt="bildschirmfoto 2018-08-23 um 23 02 59" src="https://user-images.githubusercontent.com/454817/44551884-c460aa80-a728-11e8-8159-845be7bb2ba5.png">

4) Then select the build target in the menu:

<img width="208" alt="bildschirmfoto 2018-08-23 um 22 53 32" src="https://user-images.githubusercontent.com/454817/44551902-cfb3d600-a728-11e8-8bb2-d80a41df5e88.png">

5) Go to: "Edit Scheme...":

<img width="256" alt="bildschirmfoto 2018-08-23 um 22 53 36" src="https://user-images.githubusercontent.com/454817/44551914-db9f9800-a728-11e8-978c-215ed39268e2.png">

6) Select "Run" and:

7) Disable the "Debug executable toggle"

<img width="892" alt="bildschirmfoto 2018-08-23 um 23 13 30" src="https://user-images.githubusercontent.com/454817/44552468-b449ca80-a72a-11e8-86a9-0e538f4ccece.png">

8) Click on the combobox that says "auvaltool"-> Select: "Other..." and select the "auval" executable you just copied to /Applications

<img width="895" alt="bildschirmfoto 2018-08-23 um 23 13 37" src="https://user-images.githubusercontent.com/454817/44552522-d8a5a700-a72a-11e8-9517-be77e7ff5f54.png">

9) Now select "Run" -> Switch to "Arguments" tab:

<img width="891" alt="bildschirmfoto 2018-08-23 um 22 53 43" src="https://user-images.githubusercontent.com/454817/44551922-e3f7d300-a728-11e8-93b9-4eb53055fb2f.png">

10) Instead of `-v aufx Ipef Acme`, which is dummy data and totally wrong, put `-v aufx $PLUG_UNIQUE_ID $PLUG_MFR_ID`, i.e.: `-v aufx Lapa AHVI`

=> FINALLY, run the task again, and...

<img width="1406" alt="bildschirmfoto 2018-08-23 um 23 19 52" src="https://user-images.githubusercontent.com/454817/44552581-0f7bbd00-a72b-11e8-995d-e5a8e93c865c.png">

IT WORKS! 

@olilarkin Maybe we can improve the `duplicate.py` by adding two more arguments to specify set the `PLUG_UNIQUE_ID` and `PLUG_MFR_ID` and replace them automatically in `resource.h` and the Xcode schema config. Maybe I could take a look at it and pull request. Because: If new users start using this project they even might think it doesn't work "at all" when the first thing that happens after clicking "Build" is an "Internal error" :))

**Comment by olilarkin** [comment] 2018-08-23 21:38
thanks, there are some updates to the duplicate.py coming in iPlug2, with PLUG_UNIQUE_ID and PLUG_MFR_ID getting randomised on duplication. I didn't know you could get $PLUG_UNIQUE_ID $PLUG_MFR_ID in the auval args list.

**Comment by 141592653** [comment] 2018-09-12 17:01
I'm sorry, I'm very new to all of this but can I build AU devices on Windows? I couldn't see a corresponding solution on VS17. You can smash my fingers if I'm a bit too bold

**Comment by olilarkin** [comment] 2018-09-12 17:02
no. please use the wdl forum, not github issues for questions like this

**Comment by olilarkin** [comment] 2018-09-12 23:04
closing this since it's not a bug

**Closed by olilarkin** 2018-09-12 23:04 UTC
